# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

matrix:
  include:
  - php: 7.0
  - php: 7.1
  - php: 7.2
  - php: 7.3

notifications:
  email: false

script: phpunit --strict-coverage --strict-global-state --configuration phpunit.xml --coverage-text

