# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

matrix:
  include:
  - php: 7.0
  - php: 7.1
  - php: 7.2
  - php: 7.3

notifications:
  email: false

install:
  - if [[ $TRAVIS_PHP_VERSION = '7.0']]; then wget -O vendor/bin/phpunit https://phar.phpunit.de/phpunit-6.5.14.phar; fi
  - if [[ $TRAVIS_PHP_VERSION = '7.1']]; then wget -O vendor/bin/phpunit https://phar.phpunit.de/phpunit-7.5.16.phar; fi

script:
  - phpunit --strict-coverage --strict-global-state --configuration phpunit.xml --coverage-text

