# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

matrix:
  include:
  - php: 7.0
  - php: 7.1
  - php: 7.2
  - php: 7.3

notifications:
  email: false

install:
  - if [ $TRAVIS_PHP_VERSION = '7.0']; then mkdir -p phpunit/bin; wget -O phpunit/bin/phpunit https://phar.phpunit.de/phpunit-6.5.14.phar; export PATH=`pwd`/phpunit/bin:$PATH; fi
  - if [ $TRAVIS_PHP_VERSION = '7.1']; then mkdir -p phpunit/bin; wget -O phpunit/bin/phpunit https://phar.phpunit.de/phpunit-7.5.16.phar; export PATH=`pwd`/phpunit/bin:$PATH; fi

script:
  - phpunit --strict-coverage --strict-global-state --configuration phpunit.xml --coverage-text

